### ISSUE TITLE
User Pause not honored during song/station change or buffering.

### ISSUE THREAD

**Issue by JasonLG1979** [pithos/pithos#213]
Expected behavior(IMHO) - 
Whenever I click pause(even during buffering) Pithos should say paused until I click play. If I click pause then skip a song or load a new station the next/new song should buffer but not start playing until I click play.

Current  behavior - 
Pause during buffering works sometimes. If I click pause then skip to the next song/load a new station the song buffers and start playing automatically even though I did not click play.

IMHO Pause should never be overridden. 

I can fix this. I just want your thoughts on this @TingPing and @gregsheremeta before I go down that rabbit hole.

**Comment by TingPing** [comment]
I don't like that behavior. The act of hitting next or changing stations implies "I want to listen to something else", at least to me.

**Comment by gregsheremeta** [comment]
I agree with @JasonLG1979 on it, but we may be wrong. It'd be interesting to see if there's a convention or spec on it (since ultimately, these buttons constitute a ubiquitous interface). What do media players, DVD players, VLC, Windows Media Player, etc. do?

**Comment by gregsheremeta** [comment]
VLC starts playing after skip while paused.

**Comment by JasonLG1979** [comment]
Ok, I guess we shouldn't care about pause going into a new song. What about being able to pause during buffering?

**Comment by TingPing** [comment]
Pausing during buffering should be respected as-is.

**Comment by JasonLG1979** [comment]
> Pausing during buffering should be respected as-is.

? But it's not respected.

**Comment by gregsheremeta** [comment]
Yeah I didn't follow @TingPing's comment either. If I'm buffering and I hit pause, it should stay paused. If it doesn't, it's a bug.

**Comment by JasonLG1979** [comment]
For aac streams I think the reason it may not be respected is that the buffer throws a couple 100% messages before it actually settles down. Causing it to go back and forth between buffering and not. I think something maybe getting lost along the way as the code in the buffering function is trying to protect user pause. 

For mp3 streams buffering usually takes less than 1 sec(for me anyway) so you pretty much have to be a ninja to actually hit pause while it's actually buffering.

**Comment by JasonLG1979** [comment]
> VLC starts playing after skip while paused.

Clementine, same behavior.

**Comment by TingPing** [comment]
https://github.com/pithos/pithos/commit/af94c55d9960c1a991c19cdd21846a01f6c3a5f5 went out of its way to make sure it respects pause during buffering, but as @JasonLG1979 mentioned the timing is rather specific.

**Comment by JasonLG1979** [comment]
I think I got this fixed in my latest PR. If you hit pause during buffering it stays paused regardless of timing or stream type.

**Comment by JasonLG1979** [comment]
> af94c55 went out of its way to make sure it respects pause during bufferin

It doesn't work.

**Comment by TingPing** [comment]
@JasonLG1979 So does this work for you now?

**Comment by JasonLG1979** [comment]
No I still can't pause during buffering. But it wasn't going anywhere.

**Comment by TingPing** [comment]
Don't just close things "Because it wasn't going anywhere" please, if a bug still exists it still needs to be fixed.

**Comment by JasonLG1979** [comment]
I took that to mean "won't fix".

**Comment by JasonLG1979** [comment]
I even submitted a pull request fixing it at one point.

**Comment by TingPing** [comment]
Sorry if it seems that way, I may not be the most responsive person for reviewing things. The main issue with this was it did seem to work for me as I said above. I also looked at your PR and made some comments on not liking the approach you made, and while I never replied again your responses never changed my mind on it.

**Comment by JasonLG1979** [comment]
It won't be a huge deal once we stop using the crappy aac mp4 streams anyway. Buffering(for me at least) is really fast with the good streams. You'd have to be sitting there trying to expose the bug to notice that you couldn't pause during buffering.

**Comment by JasonLG1979** [comment]
I'm going to call this fixed. I haven't noticed a problem in a long time. I actually forgot about this...
